export const actionTypes = {
  ADD_POSTAL_CODE: "add_service_postal_code",
  ADD_SERVICE_TYPE_CHECKBOX: "add_service_type_checkbox",
  ADD_SERVICE_MULTIPLE_CHECKBOX: "add_service_multiple_checkbox",
  ADD_MORE_SERVICE_MULTIPLE_CHECKBOX: "add_more_multiple_checkbox",
  ADD_SERVICE_OPTIONS_BOX: "add_services_optionBOX",
  ADD_SERVICE_TITLE_CHECKBOX: "add_SERVICES_cHECKBOX_TITLE",
  ADD_SERVICE_IMAGE: "add_image",
  ADD_SERVICE_COMMENT: "add_COMMENT",
  ADD_SERVICE_EMAIL: "add_EMAIL",
  ADD_INPUT_RADIO: "add_input_radio",
  ADD_DOUBLE_CHECKBOX: "add_doubleCheckbox",
  ADD_DOUBLE_TITLE_RADIO: "add_doubleTitle_radio",
  ADD_REGISTRATION_DATA: "add_registration_data",
  ADD_PRODUCT_DATA: "add_product_data",
};
